//
// FreeBayes-specific VCF filtering subworkflow
//

// include { BCFTOOLS_FILTER                    } from '../../../modules/nf-core/bcftools/filter/main'
include { BCFTOOLS_FILTER_SOMATIC        } from '../../../subworkflows/local/vcf_filter_mutect2/bcftools/filter_somatic/main'

workflow VCF_FILTER_MUTECT2 {
    take:
    ch_vcf_tbi    // channel: [ val(meta), path(vcf), path(tbi) ]
    
    main:
    ch_versions = Channel.empty()
    
    // Filter Mutect2 VCFs only
    ch_mutect2_vcfs = ch_vcf_tbi.filter{ meta, vcf, tbi -> 
        meta.variantcaller == 'mutect2' || vcf.name.contains('mutect2')
    }
    
    ch_mutect2_vcfs.map{ meta, vcf, tbi ->
        def new_id = vcf.name - '.vcf.gz'  // "A5-F4-I1-R1_vs_A0-F0-I1-R1.mutect2_snpEff.ann"
        [meta + [id: "${new_id}.quality_filtered"], vcf, tbi]
        }.set{ ch_for_basic_filter }


    BCFTOOLS_FILTER_SOMATIC(
        ch_for_basic_filter.map { meta, vcf, tbi -> [meta, vcf, tbi] },
        ch_for_basic_filter.map { meta, vcf, tbi -> meta.tumor_id },
        ch_for_basic_filter.map { meta, vcf, tbi -> meta.normal_id }
    )

    

    ch_versions = ch_versions.mix(BCFTOOLS_FILTER_SOMATIC.out.versions.first())

    // Create channel with filtered VCFs and their indices (already generated by the processes)
    ch_filtered_vcfs = BCFTOOLS_FILTER_SOMATIC.out.vcf.join(
        BCFTOOLS_FILTER_SOMATIC.out.tbi, 
        failOnDuplicate: true, 
        failOnMismatch: true
    )

    
    emit:
    vcf_filtered     = ch_filtered_vcfs           // channel: [ val(meta), path(vcf), path(tbi) ]
    versions         = ch_versions                // channel: [ path(versions.yml) ]
}
